#!/usr/bin/env bash
# run_instance.sh — run the measured operation and report the verdict.
#   args: v1 <benchmark> <instance> <params> <result-file>
#
# Everything this script does is timed, so it does as little as it can: submit the instance
# to the already-warm CORA daemon, wait for its verdict, copy it out. The operands were
# generated by prepare_instance.sh; the daemon loads them once and then performs the
# operation as often as params asks.
#
# The lease it holds for its whole lifetime is what makes a kill safe: if the harness's
# timeout SIGKILLs this process group, the kernel drops the lease and cora_server.sh tears
# the daemon down for a clean restart — even though SIGKILL cannot run a trap. If no healthy
# server is available it falls back to a direct MATLAB run, so one bad server never loses a
# whole benchmark (at the cost of a measurement that includes MATLAB startup).
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/cora_server_lib.sh"

BENCHMARK="$2"; INSTANCE="$3"; PARAMS="$4"
# The results file is always the last argument.
OUT="${@: -1}"
MATLAB_BIN="${CORA_MATLAB:-matlab}"
# Ceiling on a single instance. The harness enforces the catalog's own timeout (currently
# none), so this is only a backstop against a wedged daemon.
RUN_WAIT="${CORA_RUN_WAIT:-3600}"

# Direct fallback: a plain MATLAB run. CORA_DIRECT_CMD is a test seam:
# `<cmd> run <benchmark> <instance> <params> <out>`.
direct_run() {
    echo "[run_instance] no healthy server; running directly via MATLAB"
    if [ -n "${CORA_DIRECT_CMD:-}" ]; then
        $CORA_DIRECT_CMD run "$BENCHMARK" "$INSTANCE" "$PARAMS" "$OUT"
        return $?
    fi
    local b="${BENCHMARK//\'/\'\'}" i="${INSTANCE//\'/\'\'}"
    local p="${PARAMS//\'/\'\'}" o="${OUT//\'/\'\'}"
    "$MATLAB_BIN" -batch "addpath(genpath('$HERE')); run_instance('$b','$i','$p','$o');"
}

if ! server_alive || ! ping_ok; then
    direct_run
    exit 0
fi

# relay=0: nothing is tailed while the job runs, so neither the tail nor its drain lands in
# the measurement. The log is printed below only if the instance did not finish.
submit_job "run" "$BENCHMARK" "$INSTANCE" "$PARAMS" \
    "$SRV_DIR/result" "$RUN_WAIT" 0
case $? in
    0)  cp "$SRV_DIR/result" "$OUT"
        # Header row, then the verdict; `read` so this costs no fork on the common path.
        verdict=""
        { read -r _ && read -r verdict; } 2>/dev/null < "$OUT" || true
        [ "$verdict" = finished ] || relay_job_log
        exit 0 ;;
    1)  echo "[run_instance] could not acquire the server lease; running directly"
        direct_run; exit 0 ;;
    2)  echo "[run_instance] no verdict within ${RUN_WAIT}s; aborting (server will restart)"
        relay_job_log
        exit 124 ;;   # exiting frees the lease -> cora_server.sh kills the wedged daemon
esac
